//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var IngestedDocuments = newIngestedDocumentsTable("public", "ingested_documents", "")

type ingestedDocumentsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	DocumentType postgres.ColumnString
	ExternalID   postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz
	UpdatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type IngestedDocumentsTable struct {
	ingestedDocumentsTable

	EXCLUDED ingestedDocumentsTable
}

// AS creates new IngestedDocumentsTable with assigned alias
func (a IngestedDocumentsTable) AS(alias string) *IngestedDocumentsTable {
	return newIngestedDocumentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new IngestedDocumentsTable with assigned schema name
func (a IngestedDocumentsTable) FromSchema(schemaName string) *IngestedDocumentsTable {
	return newIngestedDocumentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new IngestedDocumentsTable with assigned table prefix
func (a IngestedDocumentsTable) WithPrefix(prefix string) *IngestedDocumentsTable {
	return newIngestedDocumentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new IngestedDocumentsTable with assigned table suffix
func (a IngestedDocumentsTable) WithSuffix(suffix string) *IngestedDocumentsTable {
	return newIngestedDocumentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newIngestedDocumentsTable(schemaName, tableName, alias string) *IngestedDocumentsTable {
	return &IngestedDocumentsTable{
		ingestedDocumentsTable: newIngestedDocumentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newIngestedDocumentsTableImpl("", "excluded", ""),
	}
}

func newIngestedDocumentsTableImpl(schemaName, tableName, alias string) ingestedDocumentsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		DocumentTypeColumn = postgres.StringColumn("document_type")
		ExternalIDColumn   = postgres.StringColumn("external_id")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampzColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, DocumentTypeColumn, ExternalIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{DocumentTypeColumn, ExternalIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns     = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return ingestedDocumentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		DocumentType: DocumentTypeColumn,
		ExternalID:   ExternalIDColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
